"""
models.py — SQLAlchemy ORM models.
"""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Integer, JSON, String, Text

from database import Base


class Report(Base):
    __tablename__ = "reports"

    # Primary key — UUID string generated by the bot
    id = Column(String(36), primary_key=True)

    # Human-readable URL slug, e.g. "eating-late-causes-weight-gain-a1b2c3"
    slug = Column(String(120), unique=True, index=True, nullable=False)

    # Original Instagram URL
    reel_url = Column(Text, nullable=False)

    # SHA-256 prefix of reel_url — used for fast duplicate detection
    url_hash = Column(String(16), unique=True, index=True, nullable=False)

    # Analysis fields
    claim = Column(Text, nullable=False)
    transcript_summary = Column(Text, default="")
    domain = Column(String(80), default="General")
    evidence_level = Column(String(60), default="Unknown")
    red_flags = Column(JSON, default=list)          # list[str]
    explanation = Column(Text, default="")
    credibility_score = Column(Integer, nullable=False)
    verdict = Column(String(40), nullable=False)

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    published_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
